## 1. Chargement & aperçu

In [2]:
import polars as pl
pl.Config.set_tbl_rows(20)
pl.Config.set_fmt_str_lengths(60)
pl.Config.set_tbl_width_chars(200)

polars.config.Config

In [3]:
read_csv_options = {"infer_schema_length": None}
df_container = pl.read_csv("./tables athena/dict_dico_container.csv", **read_csv_options)
df_field     = pl.read_csv("./tables athena/difi_dico_field.csv",     **read_csv_options)
df_structure = pl.read_csv("./tables athena/dist_dico_structure.csv", **read_csv_options)
df_entt      = pl.read_csv("./tables athena/lien_link_entt.csv",      **read_csv_options)
df_source    = pl.read_csv("./tables athena/diso_dico_source.csv",    **read_csv_options)
df_usage     = pl.read_csv("./tables athena/usag_usage.csv",     **read_csv_options)


tables = {
    "source":    df_source,
    "container": df_container,
    "structure": df_structure,
    "field":     df_field,
    "link":      df_entt,
        "usage":     df_usage,

}

## 2. Volumétrie & structure de chaque table

In [ ]:
print(f"{'Table':<15} {'Lignes':>8} {'Colonnes':>10} {'Nulls total':>14} {'Str cols':>10} {'Num cols':>10}")
for name, df in tables.items():
    n_rows    = df.shape[0]
    n_cols    = df.shape[1]
    n_nulls   = sum(df[c].null_count() for c in df.columns)
    n_str     = sum(1 for c in df.columns if df[c].dtype == pl.Utf8)
    n_num     = sum(1 for c in df.columns if df[c].dtype in (pl.Int64, pl.Float64, pl.Int32))
    print(f"{name:<15} {n_rows:>8} {n_cols:>10} {n_nulls:>14} {n_str:>10} {n_num:>10}")

Table             Lignes   Colonnes    Nulls total   Str cols   Num cols
source               543         26            543         24          2
container          19467         25          94113         23          2
structure         328159         36        2297113         34          2
field            2082956         40        6248890         31          1
link              641100         15             63         15          0
usage              95315         98        1320430         84          9

In [ ]:
def schema_detail(df, name):
    print(f"  {name.upper()}")
    print(f"  {'Colonne':<38} {'Type':>12} {'Nulls':>8} {'%Null':>8} {'Uniques':>10}")
    for col in df.columns:
        dtype   = str(df[col].dtype)
        n_null  = df[col].null_count()
        pct     = round(n_null / df.shape[0] * 100, 1)
        n_uniq  = df[col].n_unique()
        print(f"  {col:<38} {dtype:>12} {n_null:>8} {pct:>7}% {n_uniq:>10}")

for name, df in tables.items():
    schema_detail(df, name)

  SOURCE
  Colonne                                        Type    Nulls    %Null    Uniques
  d_extract                                    String        0     0.0%          1
  v_ident_works                                String        0     0.0%          1
  v_tech_ident_entt                            String        0     0.0%        543
  v_ident_vers                                 String        0     0.0%          1
  v_func_name_entt                             String        0     0.0%        536
  v_tech_name_entt                             String        0     0.0%        537
  v_path                                       String        0     0.0%        537
  v_type_path                                  String        0     0.0%          3
  v_type_entt                                  String        0     0.0%          3
  v_data_type_entt                             String        0     0.0%          1
  v_loct_entt_dlk                              String        0     0.0%        543
  v_url_entt_dlk                               String        0     0.0%        543
  n_chil_count                                  Int64        0     0.0%        270
  v_status_entt                                String        0     0.0%          5
  v_desc_entt                                  String        0     0.0%         82
  s_cre_entt                                   String        0     0.0%        521
  s_last_modif_entt                            String        0     0.0%        457
  n_perc_doc                                  Float64        0     0.0%         18
  v_class_cmnt                                 String        0     0.0%          8
  c_applic                                     String        0     0.0%        450
  v_curr_techno                                String      543   100.0%          1
  d_valid                                      String        0     0.0%         26
  v_host_mode                                  String        0     0.0%          9
  v_lvl_class                                  String        0     0.0%          5
  c_techno                                     String        0     0.0%         20
  v_train_applic                               String        0     0.0%         17
  CONTAINER
  Colonne                                        Type    Nulls    %Null    Uniques
  d_extract                                    String        0     0.0%          1
  v_ident_works                                String        0     0.0%          1
  v_tech_ident_entt                            String        0     0.0%      19467
  v_ident_vers                                 String        0     0.0%          1
  v_func_name_entt                             String        0     0.0%       8253
  v_tech_name_entt                             String        0     0.0%       8239
  v_path                                       String        0     0.0%      19467
  v_type_path                                  String        0     0.0%         19
  v_type_entt                                  String        0     0.0%          2
  v_data_type_entt                             String        0     0.0%          1
  v_loct_entt_dlk                              String        0     0.0%      19467
  v_url_entt_dlk                               String        0     0.0%      19467
  n_chil_count                                  Int64        0     0.0%       1149
  v_status_entt                                String        0     0.0%          5
  v_desc_entt                                  String    16474    84.6%       2167
  s_cre_entt                                   String        0     0.0%       1596
  s_last_modif_entt                            String        0     0.0%       1636
  n_perc_doc                                    Int64        0     0.0%          7
  c_applic                                     String    19324    99.3%         68
  v_curr_techno                                String    19467   100.0%          1
  d_valid                                      String    19381    99.6%         27
  v_train_applic                               String    19467   100.0%          1
  v_drct_prnt_entt_ident                       String        0     0.0%       9094
  v_drct_prnt_entt_type                        String        0     0.0%          5
  v_drct_prnt_entt_data_type                   String        0     0.0%          2
  STRUCTURE
  Colonne                                        Type    Nulls    %Null    Uniques
  d_extract                                    String        0     0.0%          1
  v_ident_works                                String        0     0.0%          1
  v_tech_ident_entt                            String        0     0.0%     328159
  v_ident_vers                                 String        0     0.0%          1
  v_func_name_entt                             String        0     0.0%      39057
  v_tech_name_entt                             String        0     0.0%      36496
  v_path                                       String        0     0.0%     328156
  v_type_path                                  String        0     0.0%         85
  v_type_entt                                  String        0     0.0%          5
  v_data_type_entt                             String        0     0.0%          1
  v_loct_entt_dlk                              String        0     0.0%     328159
  v_url_entt_dlk                               String        0     0.0%     328159
  n_chil_count                                  Int64        0     0.0%        758
  v_status_entt                                String        0     0.0%          5
  v_summary                                    String        0     0.0%       1836
  v_desc_entt                                  String        0     0.0%       6713
  s_cre_entt                                   String        0     0.0%      22542
  s_last_modif_entt                            String        0     0.0%      32036
  d_valid                                      String        0     0.0%        188
  v_train_applic                               String        0     0.0%         21
  n_perc_doc                                   String   328159   100.0%          1
  v_primr_key_tech_name                        String   328159   100.0%          1
  v_tech_cmnt                                  String        0     0.0%      13400
  v_drct_prnt_entt_ident                       String        0     0.0%     134672
  v_drct_prnt_entt_type                        String        0     0.0%          8
  v_drct_prnt_entt_data_type                   String        0     0.0%          3
  v_type_topic                                 String   328159   100.0%          1
  n_perc_fonc_topic                             Int64        0     0.0%          2
  n_perc_fonc_data                             String   328159   100.0%          1
  n_perc_lib_fr                                String   328159   100.0%          1
  n_perc_glos_data                             String   328159   100.0%          1
  n_perc_sourc_data                            String   328159   100.0%          1
  b_topic_conf_ent                             String        0     0.0%          3
  b_topic_exh_data                             String        0     0.0%          2
  b_topic_desc                                 String        0     0.0%          3
  b_event_conf_schema                          String        0     0.0%          3
  FIELD
  Colonne                                        Type    Nulls    %Null    Uniques
  d_extract                                    String        0     0.0%          1
  v_ident_works                                String        0     0.0%          1
  v_tech_ident_entt                            String        0     0.0%    2082955
  v_ident_vers                                 String        0     0.0%          2
  v_func_name_entt                             String        0     0.0%     200782
  v_tech_name_entt                             String        0     0.0%     195812
  v_path                                       String        0     0.0%    2082941
  v_type_path                                  String        0     0.0%         84
  v_type_entt                                  String        0     0.0%          3
  v_data_type_entt                             String        0     0.0%          2
  v_loct_entt_dlk                              String        0     0.0%    2082955
  v_url_entt_dlk                               String        0     0.0%    2082955
  n_chil_count                                 String  2082956   100.0%          1
  v_status_entt                                String        0     0.0%          6
  v_summary                                    String        0     0.0%      12932
  v_desc_entt                                  String        0     0.0%      48752
  s_cre_entt                                   String        2     0.0%     127247
  s_last_modif_entt                            String        2     0.0%     168508
  c_applic                                     String  2082956   100.0%          1
  d_valid                                      String        0     0.0%         81
  v_tech_cmnt                                  String        0     0.0%      65828
  v_lvl_class                                  String        0     0.0%          6
  v_class_cmnt                                 String        0     0.0%       8472
  v_train_applic                               String        0     0.0%         20
  b_mdt                                       Boolean        2     0.0%          3
  b_primr_key                                 Boolean        2     0.0%          3
  b_frgn_key                                  Boolean        2     0.0%          3
  b_tech_data                                 Boolean        2     0.0%          3
  b_gdpr_pers_data                            Boolean        2     0.0%          3
  b_gdpr_sensi_data                           Boolean        2     0.0%          3
  v_class_propagation                          String        0     0.0%          4
  v_dacp_propagation                           String        0     0.0%          4
  n_col_size                                    Int64        2     0.0%        368
  v_col_data_type                              String        0     0.0%        272
  v_col_data_type_size                         String  2082956   100.0%          1
  v_drct_prnt_entt_ident                       String        0     0.0%     254393
  v_drct_prnt_entt_type                        String        0     0.0%          6
  v_drct_prnt_entt_data_type                   String        0     0.0%          2
  b_loca_data                                 Boolean        2     0.0%          3
  v_donnee_golden_source                      Boolean        2     0.0%          3
  LINK
  Colonne                                        Type    Nulls    %Null    Uniques
  d_extract                                    String        0     0.0%          1
  v_ident_works                                String        0     0.0%          1
  v_tech_ident_entt                            String        0     0.0%     256373
  v_func_name_entt                             String        0     0.0%      75501
  v_tech_name_entt                             String        0     0.0%      82612
  v_type_entt                                  String        0     0.0%         32
  v_data_type_entt                             String        0     0.0%          7
  v_desc_nature_link                           String        0     0.0%         23
  v_ident_tech_entt_output                     String        0     0.0%     226732
  v_name_func_entt_output                      String       12     0.0%      89059
  v_name_tech_entt_output                      String       12     0.0%      87819
  v_name_type_entt_output                      String        0     0.0%         35
  v_name_data_type_entt_output                 String       39     0.0%          9
  v_name_type_path_entt_output                 String        0     0.0%        257
  v_name_path_entt_output                      String        0     0.0%     226513

In [ ]:
for name, df in tables.items():
    print(f" {name.upper()}")
    display(df.head())

 SOURCE

shape: (5, 26)
┌────────────┬───────────────────────────────────────────┬──────────────────────────────────────────┬──────────────────────────────────────┬───┬─────────────┬─────────────┬──────────┬────────────────┐
│ d_extract  ┆ v_ident_works                             ┆ v_tech_ident_entt                        ┆ v_ident_vers                         ┆ … ┆ v_host_mode ┆ v_lvl_class ┆ c_techno ┆ v_train_applic │
│ ---        ┆ ---                                       ┆ ---                                      ┆ ---                                  ┆   ┆ ---         ┆ ---         ┆ ---      ┆ ---            │
│ str        ┆ str                                       ┆ str                                      ┆ str                                  ┆   ┆ str         ┆ str         ┆ str      ┆ str            │
╞════════════╪═══════════════════════════════════════════╪══════════════════════════════════════════╪══════════════════════════════════════╪═══╪═════════════╪═════════════╪══════════╪════════════════╡
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59f3 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:4df ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆             ┆             ┆          ┆                │
│            ┆ 7279-3a9e-4025-956c…                      ┆ 73410-8ea4-4273-affd…                    ┆                                      ┆   ┆             ┆             ┆          ┆                │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59f3 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:f5e ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆             ┆             ┆          ┆                │
│            ┆ 7279-3a9e-4025-956c…                      ┆ 6b0ed-7e92-4601-8c7d…                    ┆                                      ┆   ┆             ┆             ┆          ┆                │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59f3 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:745 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆             ┆             ┆          ┆                │
│            ┆ 7279-3a9e-4025-956c…                      ┆ 6066c-42b1-473e-91c3…                    ┆                                      ┆   ┆             ┆             ┆          ┆                │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59f3 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:93e ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆             ┆             ┆          ┆                │
│            ┆ 7279-3a9e-4025-956c…                      ┆ 37d9d-7ac0-45b3-8769…                    ┆                                      ┆   ┆             ┆             ┆          ┆                │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59f3 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:998 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆             ┆             ┆          ┆                │
│            ┆ 7279-3a9e-4025-956c…                      ┆ db59e-1fcc-4653-87d8…                    ┆                                      ┆   ┆             ┆             ┆          ┆                │
└────────────┴───────────────────────────────────────────┴──────────────────────────────────────────┴──────────────────────────────────────┴───┴─────────────┴─────────────┴──────────┴────────────────┘

 CONTAINER

shape: (5, 25)
┌───────────┬────────────────────────────┬────────────────────────────┬───────────────────────────┬───┬────────────────┬───────────────────────────┬───────────────────────┬───────────────────────────┐
│ d_extract ┆ v_ident_works              ┆ v_tech_ident_entt          ┆ v_ident_vers              ┆ … ┆ v_train_applic ┆ v_drct_prnt_entt_ident    ┆ v_drct_prnt_entt_type ┆ v_drct_prnt_entt_data_typ │
│ ---       ┆ ---                        ┆ ---                        ┆ ---                       ┆   ┆ ---            ┆ ---                       ┆ ---                   ┆ e                         │
│ str       ┆ str                        ┆ str                        ┆ str                       ┆   ┆ str            ┆ str                       ┆ str                   ┆ ---                       │
│           ┆                            ┆                            ┆                           ┆   ┆                ┆                           ┆                       ┆ str                       │
╞═══════════╪════════════════════════════╪════════════════════════════╪═══════════════════════════╪═══╪════════════════╪═══════════════════════════╪═══════════════════════╪═══════════════════════════╡
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c-08 ┆ 59f37279-3a9e-4025-956c-08 ┆ 7333a87f-1f0f-4cc7-8d81-f ┆ … ┆ null           ┆ 59f37279-3a9e-4025-956c-0 ┆ Directory             ┆ Container                 │
│           ┆ 8a0c8f217d:59f37279-3a9e-4 ┆ 8a0c8f217d:053dacd0-b9f8-4 ┆ cc2b283d433               ┆   ┆                ┆ 88a0c8f217d:f649e632-2845 ┆                       ┆                           │
│           ┆ 025-956c…                  ┆ 94c-a3a9…                  ┆                           ┆   ┆                ┆ -4d2a-b446…               ┆                       ┆                           │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c-08 ┆ 59f37279-3a9e-4025-956c-08 ┆ 7333a87f-1f0f-4cc7-8d81-f ┆ … ┆ null           ┆ 59f37279-3a9e-4025-956c-0 ┆ Directory             ┆ Container                 │
│           ┆ 8a0c8f217d:59f37279-3a9e-4 ┆ 8a0c8f217d:17ec4c4a-e752-4 ┆ cc2b283d433               ┆   ┆                ┆ 88a0c8f217d:5c213f51-704d ┆                       ┆                           │
│           ┆ 025-956c…                  ┆ b08-9ea8…                  ┆                           ┆   ┆                ┆ -4171-820c…               ┆                       ┆                           │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c-08 ┆ 59f37279-3a9e-4025-956c-08 ┆ 7333a87f-1f0f-4cc7-8d81-f ┆ … ┆ null           ┆ 59f37279-3a9e-4025-956c-0 ┆ Directory             ┆ Container                 │
│           ┆ 8a0c8f217d:59f37279-3a9e-4 ┆ 8a0c8f217d:3d605460-05d6-4 ┆ cc2b283d433               ┆   ┆                ┆ 88a0c8f217d:fdc84e4c-b45e ┆                       ┆                           │
│           ┆ 025-956c…                  ┆ adf-8a9c…                  ┆                           ┆   ┆                ┆ -4400-8f27…               ┆                       ┆                           │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c-08 ┆ 59f37279-3a9e-4025-956c-08 ┆ 7333a87f-1f0f-4cc7-8d81-f ┆ … ┆ null           ┆ 59f37279-3a9e-4025-956c-0 ┆ NoSql                 ┆ Source                    │
│           ┆ 8a0c8f217d:59f37279-3a9e-4 ┆ 8a0c8f217d:51f64341-6ec4-4 ┆ cc2b283d433               ┆   ┆                ┆ 88a0c8f217d:34046039-1018 ┆                       ┆                           │
│           ┆ 025-956c…                  ┆ abc-a9b7…                  ┆                           ┆   ┆                ┆ -4ab8-9c5b…               ┆                       ┆                           │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c-08 ┆ 59f37279-3a9e-4025-956c-08 ┆ 7333a87f-1f0f-4cc7-8d81-f ┆ … ┆ null           ┆ 59f37279-3a9e-4025-956c-0 ┆ Directory             ┆ Container                 │
│           ┆ 8a0c8f217d:59f37279-3a9e-4 ┆ 8a0c8f217d:5cbf2e5a-768b-4 ┆ cc2b283d433               ┆   ┆                ┆ 88a0c8f217d:8d8bfbde-37c8 ┆                       ┆                           │
│           ┆ 025-956c…                  ┆ 7cd-b191…                  ┆                           ┆   ┆                ┆ -4306-8874…               ┆                       ┆                           │
└───────────┴────────────────────────────┴────────────────────────────┴───────────────────────────┴───┴────────────────┴───────────────────────────┴───────────────────────┴───────────────────────────┘

 STRUCTURE

shape: (5, 36)
┌────────────┬───────────────────────────────────┬───────────────────────────────────┬──────────────────────────────────┬───┬──────────────────┬──────────────────┬──────────────┬─────────────────────┐
│ d_extract  ┆ v_ident_works                     ┆ v_tech_ident_entt                 ┆ v_ident_vers                     ┆ … ┆ b_topic_conf_ent ┆ b_topic_exh_data ┆ b_topic_desc ┆ b_event_conf_schema │
│ ---        ┆ ---                               ┆ ---                               ┆ ---                              ┆   ┆ ---              ┆ ---              ┆ ---          ┆ ---                 │
│ str        ┆ str                               ┆ str                               ┆ str                              ┆   ┆ str              ┆ str              ┆ str          ┆ str                 │
╞════════════╪═══════════════════════════════════╪═══════════════════════════════════╪══════════════════════════════════╪═══╪══════════════════╪══════════════════╪══════════════╪═════════════════════╡
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283 ┆ … ┆ Non contrôlé     ┆ Non contrôlé     ┆ Non contrôlé ┆ Non contrôlé        │
│            ┆ 17d:59f37279-3a9e-4025-956c…      ┆ 17d:14d476d5-5b23-407c-bc3d…      ┆ d433                             ┆   ┆                  ┆                  ┆              ┆                     │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283 ┆ … ┆ Non contrôlé     ┆ Non contrôlé     ┆ Non contrôlé ┆ Non contrôlé        │
│            ┆ 17d:59f37279-3a9e-4025-956c…      ┆ 17d:14ff8253-4c7e-4274-bba5…      ┆ d433                             ┆   ┆                  ┆                  ┆              ┆                     │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283 ┆ … ┆ Non contrôlé     ┆ Non contrôlé     ┆ Non contrôlé ┆ Non contrôlé        │
│            ┆ 17d:59f37279-3a9e-4025-956c…      ┆ 17d:151ed6c6-1e95-4366-a95f…      ┆ d433                             ┆   ┆                  ┆                  ┆              ┆                     │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283 ┆ … ┆ Non contrôlé     ┆ Non contrôlé     ┆ Non contrôlé ┆ Non contrôlé        │
│            ┆ 17d:59f37279-3a9e-4025-956c…      ┆ 17d:152490e6-6fc8-4044-835e…      ┆ d433                             ┆   ┆                  ┆                  ┆              ┆                     │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 59f37279-3a9e-4025-956c-088a0c8f2 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283 ┆ … ┆ Non contrôlé     ┆ Non contrôlé     ┆ Non contrôlé ┆ Non contrôlé        │
│            ┆ 17d:59f37279-3a9e-4025-956c…      ┆ 17d:1530f505-1129-477a-ae60…      ┆ d433                             ┆   ┆                  ┆                  ┆              ┆                     │
└────────────┴───────────────────────────────────┴───────────────────────────────────┴──────────────────────────────────┴───┴──────────────────┴──────────────────┴──────────────┴─────────────────────┘

 FIELD

shape: (5, 40)
┌────────────┬─────────────────────────────┬─────────────────────────────┬─────────────────────────────┬───┬───────────────────────┬────────────────────────────┬─────────────┬────────────────────────┐
│ d_extract  ┆ v_ident_works               ┆ v_tech_ident_entt           ┆ v_ident_vers                ┆ … ┆ v_drct_prnt_entt_type ┆ v_drct_prnt_entt_data_type ┆ b_loca_data ┆ v_donnee_golden_source │
│ ---        ┆ ---                         ┆ ---                         ┆ ---                         ┆   ┆ ---                   ┆ ---                        ┆ ---         ┆ ---                    │
│ str        ┆ str                         ┆ str                         ┆ str                         ┆   ┆ str                   ┆ str                        ┆ bool        ┆ bool                   │
╞════════════╪═════════════════════════════╪═════════════════════════════╪═════════════════════════════╪═══╪═══════════════════════╪════════════════════════════╪═════════════╪════════════════════════╡
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088 ┆                             ┆                             ┆ … ┆                       ┆                            ┆ null        ┆ null                   │
│            ┆ a0c8f217d:59f37279-3a9e-402 ┆                             ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│            ┆ 5-956c…                     ┆                             ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088 ┆                             ┆                             ┆ … ┆                       ┆                            ┆ null        ┆ null                   │
│            ┆ a0c8f217d:59f37279-3a9e-402 ┆                             ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│            ┆ 5-956c…                     ┆                             ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ 7333a87f-1f0f-4cc7-8d81-fcc ┆ … ┆ SubStructure          ┆ Structure                  ┆ false       ┆ false                  │
│            ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:1dab9051-0598-47f ┆ 2b283d433                   ┆   ┆                       ┆                            ┆             ┆                        │
│            ┆ 5-956c…                     ┆ 0-a148…                     ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ 7333a87f-1f0f-4cc7-8d81-fcc ┆ … ┆ SubStructure          ┆ Structure                  ┆ false       ┆ false                  │
│            ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:70067f2a-698b-4de ┆ 2b283d433                   ┆   ┆                       ┆                            ┆             ┆                        │
│            ┆ 5-956c…                     ┆ 8-8c2d…                     ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
│ 2026-03-06 ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ 7333a87f-1f0f-4cc7-8d81-fcc ┆ … ┆ SubStructure          ┆ Structure                  ┆ false       ┆ false                  │
│            ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:700ee016-d7cb-404 ┆ 2b283d433                   ┆   ┆                       ┆                            ┆             ┆                        │
│            ┆ 5-956c…                     ┆ 1-bcbb…                     ┆                             ┆   ┆                       ┆                            ┆             ┆                        │
└────────────┴─────────────────────────────┴─────────────────────────────┴─────────────────────────────┴───┴───────────────────────┴────────────────────────────┴─────────────┴────────────────────────┘

 LINK

shape: (5, 15)
┌───────────┬──────────────────────────┬─────────────────────────┬─────────────────────────┬───┬─────────────────────────┬─────────────────────────┬─────────────────────────┬─────────────────────────┐
│ d_extract ┆ v_ident_works            ┆ v_tech_ident_entt       ┆ v_func_name_entt        ┆ … ┆ v_name_type_entt_output ┆ v_name_data_type_entt_o ┆ v_name_type_path_entt_o ┆ v_name_path_entt_output │
│ ---       ┆ ---                      ┆ ---                     ┆ ---                     ┆   ┆ ---                     ┆ utput                   ┆ utput                   ┆ ---                     │
│ str       ┆ str                      ┆ str                     ┆ str                     ┆   ┆ str                     ┆ ---                     ┆ ---                     ┆ str                     │
│           ┆                          ┆                         ┆                         ┆   ┆                         ┆ str                     ┆ str                     ┆                         │
╞═══════════╪══════════════════════════╪═════════════════════════╪═════════════════════════╪═══╪═════════════════════════╪═════════════════════════╪═════════════════════════╪═════════════════════════╡
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c- ┆ 59f37279-3a9e-4025-956c ┆ dissolutionDecisionDate ┆ … ┆ BusinessTerm            ┆ Property                ┆ \Universe\Universe\Univ ┆ \Modèle Objets Métier - │
│           ┆ 088a0c8f217d:59f37279-3a ┆ -088a0c8f217d:363a0c7a- ┆                         ┆   ┆                         ┆                         ┆ erse\Concept\BusinessTe ┆ MOM\Tiers\Données       │
│           ┆ 9e-4025-956c…            ┆ 541c-4dd2-9d8b…         ┆                         ┆   ┆                         ┆                         ┆ rm                      ┆ descriptives spéci…     │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c- ┆ 59f37279-3a9e-4025-956c ┆ Date creation recording ┆ … ┆ BusinessTerm            ┆ Property                ┆ \Universe\Universe\Univ ┆ \Modèle Objets Métier - │
│           ┆ 088a0c8f217d:59f37279-3a ┆ -088a0c8f217d:fb220d73- ┆                         ┆   ┆                         ┆                         ┆ erse\Universe\BusinessT ┆ MOM\Contrat\Caractérist │
│           ┆ 9e-4025-956c…            ┆ 1d96-4ec3-9227…         ┆                         ┆   ┆                         ┆                         ┆ erm                     ┆ iques général…          │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c- ┆ 59f37279-3a9e-4025-956c ┆ Date position           ┆ … ┆ BusinessTerm            ┆ Property                ┆ \Universe\Universe\Univ ┆ \Modèle Objets Métier - │
│           ┆ 088a0c8f217d:59f37279-3a ┆ -088a0c8f217d:e9d8f166- ┆                         ┆   ┆                         ┆                         ┆ erse\Universe\BusinessT ┆ MOM\Contrat\Information │
│           ┆ 9e-4025-956c…            ┆ b879-404c-8425…         ┆                         ┆   ┆                         ┆                         ┆ erm                     ┆ s de gestion\…          │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c- ┆ 59f37279-3a9e-4025-956c ┆ Date de dernier dépôt   ┆ … ┆ BusinessTerm            ┆ Property                ┆ \Universe\Universe\Busi ┆ \Modèle Objets Métier - │
│           ┆ 088a0c8f217d:59f37279-3a ┆ -088a0c8f217d:84eb5245- ┆ Bilan Final             ┆   ┆                         ┆                         ┆ nessTerm                ┆ MOM\Evénements\Date     │
│           ┆ 9e-4025-956c…            ┆ 5770-4e2d-9084…         ┆                         ┆   ┆                         ┆                         ┆                         ┆ d'effet de l'évé…       │
│ 3/6/2026  ┆ 59f37279-3a9e-4025-956c- ┆ 59f37279-3a9e-4025-956c ┆ Date phase              ┆ … ┆ BusinessTerm            ┆ Property                ┆ \Universe\Universe\Univ ┆ \Modèle Objets Métier - │
│           ┆ 088a0c8f217d:59f37279-3a ┆ -088a0c8f217d:683e1ef8- ┆                         ┆   ┆                         ┆                         ┆ erse\Universe\BusinessT ┆ MOM\Contrat\Information │
│           ┆ 9e-4025-956c…            ┆ 4d14-4d5b-8397…         ┆                         ┆   ┆                         ┆                         ┆ erm                     ┆ s de gestion\…          │
└───────────┴──────────────────────────┴─────────────────────────┴─────────────────────────┴───┴─────────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────────┘

In [4]:
for table_name, df in tables.items():
    if "v_path" in df.columns:
        null_count = df.select(pl.col("v_path").is_null().sum()).item()
        total_count = df.height
        print(f"{table_name}: {null_count} null v_path / {total_count} rows")
    else:
        print(f"{table_name}: column v_path not found")

source: 0 null v_path / 543 rows
container: 0 null v_path / 19467 rows
structure: 0 null v_path / 328159 rows
field: 0 null v_path / 2082956 rows
link: column v_path not found
usage: 0 null v_path / 95315 rows